export const ProductsData = [
  {
    id: 1,
    categoryId: 2,
    title: "Teclado gamer",
    stock: 5,
    price: 1500,
    priceList: 2000,
    warranty: "6 meses",
    thumbnail: "https://i.ibb.co/L5d7WGQ/download.jpg",
    description: "Un teclado ergonomico y de calidad",
  },
  {
    id: 2,
    categoryId: 1,
    title: "Motherboard Asus",
    stock: 8,
    price: 9000,
    priceList: 10000,
    warranty: "3 años",
    thumbnail: "https://i.ibb.co/bJCXwby/download.jpg",
    description: "Una motherboard de calidad para la pc",
  },
  {
    id: 3,
    categoryId: 1,
    title: "Placa de video MSI 3090",
    stock: 6,
    price: 13000,
    priceList: 15000,
    warranty: "3 años",
    thumbnail: "https://i.ibb.co/BzRVpt9/download.jpg",
    description: "Una buena placa de video para poder exigirla",
  },
  {
    id: 4,
    categoryId: 2,
    title: "Mouse Logitech",
    stock: 16,
    price: 1700,
    priceList: 2125,
    warranty: "30 días",
    thumbnail: "https://i.ibb.co/f1dVtdX/download.jpg",
    description: "Mouse gamer para jugar de manera profesional",
  },
  {
    id: 5,
    categoryId: 2,
    title: "Parlantes Gamer",
    stock: 8,
    price: 36300,
    priceList: 45375,
    warranty: "1 año",
    thumbnail: "https://i.ibb.co/HDnm3td/download.jpg",
    description:
      "Los parlantes para juegos ofrecen un sonido increíblemente detallado logrando el mejor efecto de sonido.",
  },
  {
    id: 6,
    categoryId: 2,
    title: "Mouse gamer Red Dragon",
    stock: 4,
    price: 1700,
    priceList: 2125,
    warranty: "2 años",
    thumbnail: "https://i.ibb.co/C8vHpyc/download.jpg",
    description: "Mouse gamer para jugar de manera profesional",
  },
  {
    id: 7,
    categoryId: 2,
    title: "Auriculares Gamer Logitech",
    stock: 10,
    price: 10000,
    priceList: 12000,
    warranty: "2 años",
    thumbnail: "https://i.ibb.co/BfMHG2b/download.jpg",
    description:
      "Los mejores auriculares por su peso ligero y su duracion de bateria",
  },
  {
    id: 8,
    categoryId: 3,
    title: "Pc gamer sentey x10",
    stock: 2,
    price: 45000,
    priceList: 60000,
    warranty: "3 años",
    thumbnail: "https://i.ibb.co/rvrHhys/images.jpg",
    description:
      "El mejor pc para poder jugar tranquilamente sin preocupaciones",
  },
  {
    id: 9,
    categoryId: 4,
    title: "Procesador Intel I7",
    stock: 10,
    price: 4000,
    priceList: 5500,
    warranty: "1 año",
    thumbnail: "https://i.ibb.co/cNVrnCp/download.jpg",
    description: "El cerebro de tu pc",
  },
  {
    id: 10,
    categoryId: 2,
    title: "Micrófono blue yeti",
    stock: 14,
    price: 10490,
    priceList: 13115,
    warranty: "1 año",
    thumbnail: "https://i.ibb.co/ZJGS57z/download.jpg",
    description:
      "Un microfono ideal hoy en día tanto para clases, llamadas y stremear",
  },
];
